"use client"

import { useEffect, useRef, useState } from "react"
import { ArrowRight } from "lucide-react"
import { Button } from "@/components/ui/button"

export function CTA() {
  const ref = useRef<HTMLDivElement>(null)
  const [isVisible, setIsVisible] = useState(false)

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) setIsVisible(true)
      },
      { threshold: 0.3 }
    )
    if (ref.current) observer.observe(ref.current)
    return () => observer.disconnect()
  }, [])

  return (
    <section ref={ref} className="relative px-6 py-40">
      {/* Glow */}
      <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
        <div className="h-[400px] w-[400px] rounded-full bg-foreground/[0.03] blur-3xl" />
      </div>

      <div
        className={`relative z-10 mx-auto flex max-w-3xl flex-col items-center gap-8 text-center transition-all duration-700 ${
          isVisible ? "translate-y-0 opacity-100" : "translate-y-8 opacity-0"
        }`}
      >
        <h2 className="text-balance text-4xl font-bold tracking-tight md:text-6xl">
          This entire page is your proof.
        </h2>
        <p className="max-w-xl text-pretty text-lg leading-relaxed text-muted-foreground">
          Every section, every animation, every pixel on this page was generated by v0. No hand-coding. No templates. Just a prompt and a vision.
        </p>
        <Button size="lg" className="gap-2 px-10 text-base" asChild>
          <a href="https://v0.dev" target="_blank" rel="noopener noreferrer">
            Start building with v0
            <ArrowRight className="h-4 w-4" />
          </a>
        </Button>
      </div>
    </section>
  )
}
